name: Create a package for WooCommerce

on:
  push:
    branches:
      - master
  release:
    types:
      - published

jobs:
  create-zip-package:
    name: Create and upload a custom zip package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: confirmo/actions/checkout@v1

      - name: Create a distribution directory
        run: |
          mkdir confirmo-for-woocommerce
          cp -r ./* ./confirmo-for-woocommerce/

      - name: Create a zip package
        run: zip -r confirmo-for-woocommerce.zip confirmo-for-woocommerce

      - name: Upload the package
        uses: confirmo/actions/upload-artifact@v1
        with:
          name: confirmo-for-woocommerce
          path: confirmo-for-woocommerce.zip

  disable-default-assets:
    name: Disable default GitHub assets
    runs-on: ubuntu-latest

    steps:
      - name: Remove default assets
        run: gh api -X PATCH "repos/${{ github.repository }}/releases/${{ github.event.release.id }}" -F "assets=[]"
