name: Create a package for WooCommerce

on:
  push:
    branches:
      - master
  release:
    types:
      - published

jobs:
  create-zip-package:
    name: Create and upload a custom zip package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Create a distribution directory
        run: |
          mkdir -p /tmp/pkg/confirmo-for-woocommerce
          cp -r ./* /tmp/pkg/confirmo-for-woocommerce/

      - name: Create a zip package
        run: zip -r /tmp/pkg/confirmo-for-woocommerce.zip /tmp/pkg/confirmo-for-woocommerce

      - name: Upload the package
        uses: actions/upload-artifact@v3
        with:
          name: confirmo-for-woocommerce.zip
          path: /tmp/pkg/confirmo-for-woocommerce.zip

  disable-default-assets:
    name: Disable default GitHub assets
    runs-on: ubuntu-latest

    steps:
      - name: Remove default assets
        run: gh api -X PATCH "repos/${{ github.repository }}/releases/${{ github.event.release.id }}" -F "assets=[]"
