name: Create a package for WooCommerce

on:
  release:
    types:
      - published

jobs:
  create-zip-package:
    name: Create and upload a custom zip package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Create a distribution directory
        run: |
          mkdir -p /tmp/pkg/confirmo-for-woocommerce
          cp -r ./* /tmp/pkg/confirmo-for-woocommerce/

      - name: Create a zip package
        run: |
          cd /tmp/pkg
          zip -r confirmo-for-woocommerce.zip confirmo-for-woocommerce

      - name: Upload the asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: /tmp/pkg/confirmo-for-woocommerce.zip
          asset_name: confirmo-for-woocommerce.zip
          asset_content_type: application/zip
